Certain programs __MUST__ be install root to work properly. There is a hook 	in the installation to warn the user.  But maybe in the future we should 	try to install as root and failed the installation if it does not work?
	* ping/Makefile.am: Rules to try install setuid root.
	* rcp/Makefile.am: Rules to try install setuid root.
	* rlogin/Makefile.am: Rules to try install setuid root.
	* rsh/Makefile.am: Rules to try install setuid root.

diff --git a/ping/Makefile.am b/ping/Makefile.am
--- a/ping/Makefile.am
+++ b/ping/Makefile.am
@@ -15,3 +15,13 @@ ping_SOURCES = ping.c \
  ping_timestamp.c \
  ping_impl.h
 
+SUIDMODE = -o root -m 4775
+
+install-exec-hook:
+	-@$(INSTALL_PROGRAM) $(bin_PROGRAMS) $(SUIDMODE) $(AM_INSTALL_PROGRAM_FLAGS) $(DESTDIR)$(bindir)/`echo $(bin_PROGRAMS)|sed '$(transform)'` ; \
+	if test $$? -ne 0; then \
+		echo 'INSTALL-ERROR:'; \
+		echo 'INSTALL-ERROR: THIS PROGRAM($(bin_PROGRAMS)) MUST BE INSTALLED SETUID ROOT'; \
+		echo 'INSTALL-ERROR: $(INSTALL_PROGRAM) $(bin_PROGRAMS) $(SUIDMODE) $(DESTDIR)$(bindir)/$(bin_PROGRAMS)'; \
+		echo 'INSTALL-ERROR:'; \
+	fi
